services:
  - type: web
    name: basic-fullstack-api
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: ACCESS_SECRET_KEY
        sync: false
      - key: REFRESH_SECRET_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false
